<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Zone;
use Illuminate\Database\Seeder;

/**
 * Seeds West Bank cities (governorate centers) and their villages/localities as zones.
 */
class WestBankLocationsSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->locations() as $cityData) {
            $city = City::updateOrCreate(
                ['name_en' => $cityData['name_en']],
                ['name_ar' => $cityData['name_ar']]
            );

            foreach ($cityData['zones'] as $zoneData) {
                Zone::updateOrCreate(
                    [
                        'city_id' => $city->id,
                        'name_en' => $zoneData['name_en'],
                    ],
                    [
                        'name_ar' => $zoneData['name_ar'],
                    ]
                );
            }
        }
    }

    /**
     * @return list<array{name_ar: string, name_en: string, zones: list<array{name_ar: string, name_en: string}>}>
     */
    private function locations(): array
    {
        return [
            [
                'name_ar' => 'الخليل',
                'name_en' => 'Hebron',
                'zones' => [
                    ['name_ar' => 'مدينة الخليل', 'name_en' => 'Hebron City'],
                    ['name_ar' => 'حلحول', 'name_en' => 'Halhul'],
                    ['name_ar' => 'سعير', 'name_en' => "Sa'ir"],
                    ['name_ar' => 'بني نعيم', 'name_en' => "Bani Na'im"],
                    ['name_ar' => 'الشيوخ', 'name_en' => 'Ash-Shuyukh'],
                    ['name_ar' => 'بيت أمر', 'name_en' => 'Beit Ummar'],
                    ['name_ar' => 'صوريف', 'name_en' => 'Surif'],
                    ['name_ar' => 'خاراس', 'name_en' => 'Kharas'],
                    ['name_ar' => 'نوبا', 'name_en' => 'Nuba'],
                    ['name_ar' => 'بيت أولا', 'name_en' => 'Beit Ula'],
                    ['name_ar' => 'ترقوميا', 'name_en' => 'Tarqumiyah'],
                    ['name_ar' => 'إذنا', 'name_en' => 'Idhna'],
                    ['name_ar' => 'تفوح', 'name_en' => 'Taffuh'],
                    ['name_ar' => 'بيت عوا', 'name_en' => 'Beit Awwa'],
                    ['name_ar' => 'دير سامت', 'name_en' => 'Deir Sammit'],
                    ['name_ar' => 'الكوم', 'name_en' => 'Al-Kum'],
                    ['name_ar' => 'خرسا', 'name_en' => 'Khursa'],
                    ['name_ar' => 'الطبقة', 'name_en' => 'At-Tabaqa'],
                    ['name_ar' => 'الظاهرية', 'name_en' => 'Adh-Dhahiriya'],
                    ['name_ar' => 'السموع', 'name_en' => 'As-Samu'],
                    ['name_ar' => 'يطا', 'name_en' => 'Yatta'],
                    ['name_ar' => 'دورا', 'name_en' => 'Dura'],
                    ['name_ar' => 'بيت كاحل', 'name_en' => 'Beit Kahil'],
                    ['name_ar' => 'دير العسل', 'name_en' => "Deir al-'Asal"],
                    ['name_ar' => 'المجد', 'name_en' => 'Al-Majd'],
                    ['name_ar' => 'بيت مرسم', 'name_en' => 'Beit Mirsim'],
                    ['name_ar' => 'الريحية', 'name_en' => 'Ar-Rihiya'],
                    ['name_ar' => 'كرمة', 'name_en' => 'Karma'],
                    ['name_ar' => 'الفوار', 'name_en' => 'Al-Fawwar'],
                ],
            ],
            [
                'name_ar' => 'بيت لحم',
                'name_en' => 'Bethlehem',
                'zones' => [
                    ['name_ar' => 'مدينة بيت لحم', 'name_en' => 'Bethlehem City'],
                    ['name_ar' => 'بيت جالا', 'name_en' => 'Beit Jala'],
                    ['name_ar' => 'بيت ساحور', 'name_en' => 'Beit Sahour'],
                    ['name_ar' => 'الدوحة', 'name_en' => 'Ad-Doha'],
                    ['name_ar' => 'الخضر', 'name_en' => 'Al-Khader'],
                    ['name_ar' => 'أرطاس', 'name_en' => 'Artas'],
                    ['name_ar' => 'بتير', 'name_en' => 'Battir'],
                    ['name_ar' => 'حفنة', 'name_en' => 'Husan'],
                    ['name_ar' => 'نحالين', 'name_en' => 'Nahalin'],
                    ['name_ar' => 'وادي فوكين', 'name_en' => 'Wadi Fukin'],
                    ['name_ar' => 'جبعة', 'name_en' => "Al-Jab'a"],
                    ['name_ar' => 'تقوع', 'name_en' => "Tuqu'"],
                    ['name_ar' => 'زعترة', 'name_en' => "Za'tara"],
                    ['name_ar' => 'بيت فجار', 'name_en' => 'Beit Fajjar'],
                    ['name_ar' => 'العبيدية', 'name_en' => "Al-'Ubeidiya"],
                    ['name_ar' => 'دار صلاح', 'name_en' => 'Dar Salah'],
                    ['name_ar' => 'هندازة', 'name_en' => 'Hindaza'],
                    ['name_ar' => 'جورة الشمعة', 'name_en' => 'Jurat ash-Sham\'a'],
                ],
            ],
            [
                'name_ar' => 'القدس',
                'name_en' => 'Jerusalem',
                'zones' => [
                    ['name_ar' => 'البلدة القديمة', 'name_en' => 'Old City'],
                    ['name_ar' => 'العيسوية', 'name_en' => "Al-'Isawiya"],
                    ['name_ar' => 'الطور', 'name_en' => 'At-Tur'],
                    ['name_ar' => 'سلوان', 'name_en' => 'Silwan'],
                    ['name_ar' => 'جبل المكبر', 'name_en' => 'Jabal al-Mukaber'],
                    ['name_ar' => 'صور باهر', 'name_en' => 'Sur Baher'],
                    ['name_ar' => 'أم طوبا', 'name_en' => 'Umm Tuba'],
                    ['name_ar' => 'بيت حنينا', 'name_en' => 'Beit Hanina'],
                    ['name_ar' => 'شعفاط', 'name_en' => "Shu'fat"],
                    ['name_ar' => 'كفر عقب', 'name_en' => "Kafr 'Aqab"],
                    ['name_ar' => 'الرام', 'name_en' => 'Ar-Ram'],
                    ['name_ar' => 'عناتا', 'name_en' => "'Anata"],
                    ['name_ar' => 'حزما', 'name_en' => 'Hizma'],
                    ['name_ar' => 'مخماس', 'name_en' => 'Mikhmas'],
                    ['name_ar' => 'جبع', 'name_en' => "Jaba'"],
                    ['name_ar' => 'قلنديا', 'name_en' => 'Qalandiya'],
                    ['name_ar' => 'بير نبالا', 'name_en' => 'Bir Nabala'],
                    ['name_ar' => 'الجب', 'name_en' => 'Al-Jib'],
                    ['name_ar' => 'بدّو', 'name_en' => 'Biddu'],
                    ['name_ar' => 'قطنة', 'name_en' => 'Qatanna'],
                    ['name_ar' => 'بيت سوريك', 'name_en' => 'Beit Surik'],
                    ['name_ar' => 'بيت إكسا', 'name_en' => 'Beit Iksa'],
                    ['name_ar' => 'أبو ديس', 'name_en' => 'Abu Dis'],
                    ['name_ar' => 'العيزرية', 'name_en' => "Al-'Eizariya"],
                    ['name_ar' => 'السواحرة الشرقية', 'name_en' => 'As-Sawahira ash-Sharqiya'],
                ],
            ],
            [
                'name_ar' => 'رام الله والبيرة',
                'name_en' => 'Ramallah and Al-Bireh',
                'zones' => [
                    ['name_ar' => 'رام الله', 'name_en' => 'Ramallah'],
                    ['name_ar' => 'البيرة', 'name_en' => 'Al-Bireh'],
                    ['name_ar' => 'بيتونيا', 'name_en' => 'Beitunia'],
                    ['name_ar' => 'بيرزيت', 'name_en' => 'Birzeit'],
                    ['name_ar' => 'دير دبوان', 'name_en' => 'Deir Dibwan'],
                    ['name_ar' => 'سلواد', 'name_en' => 'Silwad'],
                    ['name_ar' => 'عين يبرود', 'name_en' => "'Ein Yabrud"],
                    ['name_ar' => 'دوره القرع', 'name_en' => "Dura al-Qar'"],
                    ['name_ar' => 'أبو قش', 'name_en' => 'Abu Qash'],
                    ['name_ar' => 'جفنا', 'name_en' => 'Jifna'],
                    ['name_ar' => 'عين سينيا', 'name_en' => "'Ein Sinya"],
                    ['name_ar' => 'عطارة', 'name_en' => "'Atara"],
                    ['name_ar' => 'عبوين', 'name_en' => "'Abud"],
                    ['name_ar' => 'دير جرير', 'name_en' => 'Deir Jarir'],
                    ['name_ar' => 'الطيبة', 'name_en' => 'At-Tayba'],
                    ['name_ar' => 'رمون', 'name_en' => 'Rammun'],
                    ['name_ar' => 'المزرعة الشرقية', 'name_en' => 'Al-Mazra\'a ash-Sharqiya'],
                    ['name_ar' => 'كفر مالك', 'name_en' => 'Kafr Malik'],
                    ['name_ar' => 'ترمسعيا', 'name_en' => 'Turmus\'ayya'],
                    ['name_ar' => 'سنجل', 'name_en' => 'Sinjil'],
                    ['name_ar' => 'المزرعة الغربية', 'name_en' => 'Al-Mazra\'a al-Qibliya'],
                    ['name_ar' => 'بيتلو', 'name_en' => 'Beitillu'],
                    ['name_ar' => 'دير عمار', 'name_en' => "Deir 'Ammar"],
                    ['name_ar' => 'نبي صالح', 'name_en' => 'An-Nabi Salih'],
                    ['name_ar' => 'كفر عين', 'name_en' => "Kafr 'Ein"],
                    ['name_ar' => 'قراوة بني زيد', 'name_en' => 'Qarawat Bani Zeid'],
                    ['name_ar' => 'بيت ريما', 'name_en' => 'Beit Rima'],
                    ['name_ar' => 'دير غسانة', 'name_en' => 'Deir Ghassana'],
                    ['name_ar' => 'نعلين', 'name_en' => "Ni'lin"],
                    ['name_ar' => 'بلعين', 'name_en' => "Bil'in"],
                    ['name_ar' => 'صفا', 'name_en' => 'Saffa'],
                    ['name_ar' => 'بيت عور الفوقا', 'name_en' => "Beit 'Ur al-Fauqa"],
                    ['name_ar' => 'بيت عور التحتا', 'name_en' => "Beit 'Ur at-Tahta"],
                    ['name_ar' => 'بيت سيرا', 'name_en' => 'Beit Sira'],
                    ['name_ar' => 'خربثا المصباح', 'name_en' => 'Kharbatha al-Misbah'],
                ],
            ],
            [
                'name_ar' => 'نابلس',
                'name_en' => 'Nablus',
                'zones' => [
                    ['name_ar' => 'مدينة نابلس', 'name_en' => 'Nablus City'],
                    ['name_ar' => 'بلاطة', 'name_en' => 'Balata'],
                    ['name_ar' => 'عصيرة الشمالية', 'name_en' => "'Asira ash-Shamaliya"],
                    ['name_ar' => 'طلوزة', 'name_en' => 'Talluza'],
                    ['name_ar' => 'ياصيد', 'name_en' => 'Yasid'],
                    ['name_ar' => 'بيتا', 'name_en' => 'Beita'],
                    ['name_ar' => 'حوارة', 'name_en' => 'Huwwara'],
                    ['name_ar' => 'عورتا', 'name_en' => "'Awarta"],
                    ['name_ar' => 'قبلان', 'name_en' => 'Qabalan'],
                    ['name_ar' => 'جماعين', 'name_en' => "Jamma'in"],
                    ['name_ar' => 'زيتا جماعين', 'name_en' => "Zeita Jamma'in"],
                    ['name_ar' => 'كفر قليل', 'name_en' => 'Kafr Qallil'],
                    ['name_ar' => 'روجيب', 'name_en' => 'Rujeib'],
                    ['name_ar' => 'عسكر', 'name_en' => "'Askar"],
                    ['name_ar' => 'دير الحطب', 'name_en' => 'Deir al-Hatab'],
                    ['name_ar' => 'سالم', 'name_en' => 'Salim'],
                    ['name_ar' => 'عزموط', 'name_en' => "'Azmut"],
                    ['name_ar' => 'الباذان', 'name_en' => 'Al-Badhan'],
                    ['name_ar' => 'بيت فوريك', 'name_en' => 'Beit Furik'],
                    ['name_ar' => 'بيت دجن', 'name_en' => 'Beit Dajan'],
                    ['name_ar' => 'بورين', 'name_en' => 'Burin'],
                    ['name_ar' => 'مادما', 'name_en' => 'Madama'],
                    ['name_ar' => 'عوريف', 'name_en' => "'Urif"],
                    ['name_ar' => 'تل', 'name_en' => 'Till'],
                    ['name_ar' => 'سبسطية', 'name_en' => 'Sebastia'],
                    ['name_ar' => 'النصارى', 'name_en' => 'An-Nasariya'],
                    ['name_ar' => 'عقربا', 'name_en' => "'Aqraba"],
                    ['name_ar' => 'مجدل بني فاضل', 'name_en' => 'Majdal Bani Fadil'],
                    ['name_ar' => 'جوريش', 'name_en' => 'Jurish'],
                    ['name_ar' => 'قوصرة', 'name_en' => 'Qusra'],
                ],
            ],
            [
                'name_ar' => 'جنين',
                'name_en' => 'Jenin',
                'zones' => [
                    ['name_ar' => 'مدينة جنين', 'name_en' => 'Jenin City'],
                    ['name_ar' => 'قباطية', 'name_en' => 'Qabatiya'],
                    ['name_ar' => 'يعبد', 'name_en' => "Ya'bad"],
                    ['name_ar' => 'عرابة', 'name_en' => "'Arraba"],
                    ['name_ar' => 'كفر راعي', 'name_en' => "Kafr Ra'i"],
                    ['name_ar' => 'ميثلون', 'name_en' => 'Meithalun'],
                    ['name_ar' => 'صير', 'name_en' => 'Sir'],
                    ['name_ar' => 'الجديدة', 'name_en' => 'Al-Judeida'],
                    ['name_ar' => 'برقين', 'name_en' => 'Burqin'],
                    ['name_ar' => 'كفر دان', 'name_en' => 'Kafr Dan'],
                    ['name_ar' => 'جلبون', 'name_en' => 'Jalbun'],
                    ['name_ar' => 'فقوعة', 'name_en' => "Faqqu'a"],
                    ['name_ar' => 'دير أبو ضعيف', 'name_en' => 'Deir Abu Da\'if'],
                    ['name_ar' => 'بيت قاد', 'name_en' => 'Beit Qad'],
                    ['name_ar' => 'سيلة الحارثية', 'name_en' => 'Silat al-Harithiya'],
                    ['name_ar' => 'تعنك', 'name_en' => "Ti'innik"],
                    ['name_ar' => 'زبوبا', 'name_en' => 'Zububa'],
                    ['name_ar' => 'رمانة', 'name_en' => 'Rummana'],
                    ['name_ar' => 'العرقة', 'name_en' => "Al-'Araqa"],
                    ['name_ar' => 'الطورة', 'name_en' => 'At-Tura'],
                    ['name_ar' => 'عنين', 'name_en' => "'Anin"],
                    ['name_ar' => 'الرامة', 'name_en' => 'Ar-Rama'],
                    ['name_ar' => 'مركة', 'name_en' => 'Marka'],
                    ['name_ar' => 'فحمة', 'name_en' => 'Fahma'],
                    ['name_ar' => 'الزبابدة', 'name_en' => 'Az-Zababida'],
                    ['name_ar' => 'سنور', 'name_en' => 'Sanur'],
                    ['name_ar' => 'مسلية', 'name_en' => 'Misliya'],
                    ['name_ar' => 'الجلمة', 'name_en' => 'Al-Jalama'],
                ],
            ],
            [
                'name_ar' => 'طولكرم',
                'name_en' => 'Tulkarm',
                'zones' => [
                    ['name_ar' => 'مدينة طولكرم', 'name_en' => 'Tulkarm City'],
                    ['name_ar' => 'عنبتا', 'name_en' => "'Anabta"],
                    ['name_ar' => 'بلعا', 'name_en' => "Bal'a"],
                    ['name_ar' => 'قفين', 'name_en' => 'Qaffin'],
                    ['name_ar' => 'باقة الشرقية', 'name_en' => 'Baqa ash-Sharqiya'],
                    ['name_ar' => 'نظلة عيسى', 'name_en' => "Nazlat 'Isa"],
                    ['name_ar' => 'زيتا', 'name_en' => 'Zeita'],
                    ['name_ar' => 'عتيل', 'name_en' => "'Attil"],
                    ['name_ar' => 'دير الغصون', 'name_en' => 'Deir al-Ghusun'],
                    ['name_ar' => 'علار', 'name_en' => "'Illar"],
                    ['name_ar' => 'صيدا', 'name_en' => 'Seida'],
                    ['name_ar' => 'كفر اللبد', 'name_en' => 'Kafr al-Labad'],
                    ['name_ar' => 'شوفة', 'name_en' => 'Shufa'],
                    ['name_ar' => 'فرعون', 'name_en' => "Far'un"],
                    ['name_ar' => 'كفر صور', 'name_en' => 'Kafr Sur'],
                    ['name_ar' => 'كفر عبوش', 'name_en' => "Kafr 'Abbush"],
                    ['name_ar' => 'كفر زيباد', 'name_en' => 'Kafr Zibad'],
                    ['name_ar' => 'كفر جمال', 'name_en' => 'Kafr Jammal'],
                    ['name_ar' => 'رامين', 'name_en' => 'Ramin'],
                    ['name_ar' => 'ذنابة', 'name_en' => 'Dhinnaba'],
                    ['name_ar' => 'ارتاح', 'name_en' => "Irtah"],
                ],
            ],
            [
                'name_ar' => 'قلقيلية',
                'name_en' => 'Qalqilya',
                'zones' => [
                    ['name_ar' => 'مدينة قلقيلية', 'name_en' => 'Qalqilya City'],
                    ['name_ar' => 'حبلة', 'name_en' => 'Hableh'],
                    ['name_ar' => 'عزون', 'name_en' => "'Azzun"],
                    ['name_ar' => 'كفر ثلث', 'name_en' => 'Kafr Thulth'],
                    ['name_ar' => 'جيوس', 'name_en' => 'Jayyus'],
                    ['name_ar' => 'فلامية', 'name_en' => 'Falamiya'],
                    ['name_ar' => 'كفر قدوم', 'name_en' => 'Kafr Qaddum'],
                    ['name_ar' => 'جنصافوط', 'name_en' => 'Jinsafut'],
                    ['name_ar' => 'حجة', 'name_en' => 'Hajja'],
                    ['name_ar' => 'باقة الحطب', 'name_en' => 'Baqa al-Hatab'],
                    ['name_ar' => 'كفر لاقف', 'name_en' => 'Kafr Laqif'],
                    ['name_ar' => 'إماتين', 'name_en' => 'Immatin'],
                    ['name_ar' => 'فرعتا', 'name_en' => "Far'ata"],
                    ['name_ar' => 'سنيريا', 'name_en' => 'Sanniriya'],
                    ['name_ar' => 'مسحة', 'name_en' => 'Mas-ha'],
                    ['name_ar' => 'عزون عتمة', 'name_en' => "'Azzun 'Atma"],
                    ['name_ar' => 'بيت أمين', 'name_en' => 'Beit Amin'],
                ],
            ],
            [
                'name_ar' => 'سلفيت',
                'name_en' => 'Salfit',
                'zones' => [
                    ['name_ar' => 'مدينة سلفيت', 'name_en' => 'Salfit City'],
                    ['name_ar' => 'بديا', 'name_en' => 'Bidya'],
                    ['name_ar' => 'كفر الديك', 'name_en' => 'Kafr ad-Dik'],
                    ['name_ar' => 'بروقين', 'name_en' => 'Bruqin'],
                    ['name_ar' => 'حارس', 'name_en' => 'Haris'],
                    ['name_ar' => 'كفل حارس', 'name_en' => 'Kifl Haris'],
                    ['name_ar' => 'مردا', 'name_en' => 'Marda'],
                    ['name_ar' => 'ياسوف', 'name_en' => 'Yasuf'],
                    ['name_ar' => 'إسكاكا', 'name_en' => 'Iskaka'],
                    ['name_ar' => 'فرخة', 'name_en' => 'Farkha'],
                    ['name_ar' => 'قراوة بني حسان', 'name_en' => 'Qarawat Bani Hassan'],
                    ['name_ar' => 'سرطة', 'name_en' => 'Sarta'],
                    ['name_ar' => 'رافات', 'name_en' => 'Rafat'],
                    ['name_ar' => 'دير بلوط', 'name_en' => 'Deir Ballut'],
                    ['name_ar' => 'الزاوية', 'name_en' => 'Az-Zawiya'],
                ],
            ],
            [
                'name_ar' => 'أريحا',
                'name_en' => 'Jericho',
                'zones' => [
                    ['name_ar' => 'مدينة أريحا', 'name_en' => 'Jericho City'],
                    ['name_ar' => 'العوجا', 'name_en' => "Al-'Auja"],
                    ['name_ar' => 'النويعمة', 'name_en' => "An-Nuway'ima"],
                    ['name_ar' => 'عين الديوك', 'name_en' => "'Ein ad-Duyuk"],
                    ['name_ar' => 'عقبة جبر', 'name_en' => "'Aqbat Jaber"],
                    ['name_ar' => 'مخيم عين السلطان', 'name_en' => "'Ein as-Sultan Camp"],
                    ['name_ar' => 'الديوك الفوقا', 'name_en' => 'Ad-Duyuk al-Fauqa'],
                    ['name_ar' => 'فصايل', 'name_en' => 'Fasayil'],
                    ['name_ar' => 'الجفتلك', 'name_en' => 'Al-Jiftlik'],
                    ['name_ar' => 'زبيدات', 'name_en' => 'Az-Zubeidat'],
                    ['name_ar' => 'مرجة نعجة', 'name_en' => "Marj Na'aja"],
                ],
            ],
            [
                'name_ar' => 'طوباس',
                'name_en' => 'Tubas',
                'zones' => [
                    ['name_ar' => 'مدينة طوباس', 'name_en' => 'Tubas City'],
                    ['name_ar' => 'طمون', 'name_en' => 'Tammun'],
                    ['name_ar' => 'عقابا', 'name_en' => "'Aqqaba"],
                    ['name_ar' => 'تياسير', 'name_en' => 'Tayasir'],
                    ['name_ar' => 'وادي الفارعة', 'name_en' => "Wadi al-Far'a"],
                    ['name_ar' => 'رأس الفارعة', 'name_en' => "Ras al-Far'a"],
                    ['name_ar' => 'كردلة', 'name_en' => 'Kardala'],
                    ['name_ar' => 'بردلة', 'name_en' => 'Bardala'],
                    ['name_ar' => 'عين البيضا', 'name_en' => "'Ein al-Beida"],
                    ['name_ar' => 'إبزيق', 'name_en' => 'Ibziq'],
                    ['name_ar' => 'سلحب', 'name_en' => 'Salhab'],
                    ['name_ar' => 'الثغرة', 'name_en' => 'Ath-Thaghra'],
                ],
            ],
        ];
    }
}
